/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AmountStatus.
* @enum {}
* @readonly
*/
export default class AmountStatus {
    
        /**
         * value: "StakeInProgress"
         * @const
         */
        "StakeInProgress" = "StakeInProgress";

    
        /**
         * value: "Active"
         * @const
         */
        "Active" = "Active";

    
        /**
         * value: "Rejected"
         * @const
         */
        "Rejected" = "Rejected";

    
        /**
         * value: "LimitExceeded"
         * @const
         */
        "LimitExceeded" = "LimitExceeded";

    
        /**
         * value: "Invalid"
         * @const
         */
        "Invalid" = "Invalid";

    
        /**
         * value: "UnstakeInProgress"
         * @const
         */
        "UnstakeInProgress" = "UnstakeInProgress";

    
        /**
         * value: "Withdrawable"
         * @const
         */
        "Withdrawable" = "Withdrawable";

    
        /**
         * value: "WithdrawInProgress"
         * @const
         */
        "WithdrawInProgress" = "WithdrawInProgress";

    
        /**
         * value: "Closed"
         * @const
         */
        "Closed" = "Closed";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>AmountStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AmountStatus} The enum <code>AmountStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

