/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApprovalResult.
* @enum {}
* @readonly
*/
export default class ApprovalResult {
    
        /**
         * value: 1
         * @const
         */
        "PENDING" = 1;

    
        /**
         * value: 2
         * @const
         */
        "APPROVED" = 2;

    
        /**
         * value: 3
         * @const
         */
        "REJECTED" = 3;

    
        /**
         * value: 11184809
         * @const
         */
        "unknown_default_open_api" = 11184809;

    

    /**
    * Returns a <code>ApprovalResult</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApprovalResult} The enum <code>ApprovalResult</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

