/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ApprovalStatementStatus.
* @enum {}
* @readonly
*/
export default class ApprovalStatementStatus {
    
        /**
         * value: "UnSend"
         * @const
         */
        "UnSend" = "UnSend";

    
        /**
         * value: "WaitAudit"
         * @const
         */
        "WaitAudit" = "WaitAudit";

    
        /**
         * value: "Approve"
         * @const
         */
        "Approve" = "Approve";

    
        /**
         * value: "Reject"
         * @const
         */
        "Reject" = "Reject";

    
        /**
         * value: "Invalid"
         * @const
         */
        "Invalid" = "Invalid";

    
        /**
         * value: "Timeout"
         * @const
         */
        "Timeout" = "Timeout";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>ApprovalStatementStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ApprovalStatementStatus} The enum <code>ApprovalStatementStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

