/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckAddressesValidity200ResponseInner model module.
 * @module model/CheckAddressesValidity200ResponseInner
 */
class CheckAddressesValidity200ResponseInner {
    /**
     * Constructs a new <code>CheckAddressesValidity200ResponseInner</code>.
     * @alias module:model/CheckAddressesValidity200ResponseInner
     * @param address {String} The wallet address.
     * @param validity {Boolean} Whether the address is valid.  - `true`: The address is valid.  - `false`: The address is invalid. 
     */
    constructor(address, validity) { 
        
        CheckAddressesValidity200ResponseInner.initialize(this, address, validity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, validity) { 
        obj['address'] = address;
        obj['validity'] = validity;
    }

    /**
     * Constructs a <code>CheckAddressesValidity200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckAddressesValidity200ResponseInner} obj Optional instance to populate.
     * @return {module:model/CheckAddressesValidity200ResponseInner} The populated <code>CheckAddressesValidity200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckAddressesValidity200ResponseInner();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('validity')) {
                obj['validity'] = ApiClient.convertToType(data['validity'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckAddressesValidity200ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckAddressesValidity200ResponseInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CheckAddressesValidity200ResponseInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }

        return true;
    }


}

CheckAddressesValidity200ResponseInner.RequiredProperties = ["address", "validity"];

/**
 * The wallet address.
 * @member {String} address
 */
CheckAddressesValidity200ResponseInner.prototype['address'] = undefined;

/**
 * Whether the address is valid.  - `true`: The address is valid.  - `false`: The address is invalid. 
 * @member {Boolean} validity
 */
CheckAddressesValidity200ResponseInner.prototype['validity'] = undefined;






export default CheckAddressesValidity200ResponseInner;

