/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FeeStationDestination from './FeeStationDestination';

/**
 * The FeeStationTransfer model module.
 * @module model/FeeStationTransfer
 */
class FeeStationTransfer {
    /**
     * Constructs a new <code>FeeStationTransfer</code>.
     * The information about a token transfer.
     * @alias module:model/FeeStationTransfer
     * @param token_id {String} The token ID of the transferred token. You can retrieve the IDs of all the tokens you can use by calling [List enabled tokens](https://www.cobo.com/developers/v2/api-references/wallets/list-enabled-tokens).
     */
    constructor(token_id) { 
        
        FeeStationTransfer.initialize(this, token_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token_id) { 
        obj['token_id'] = token_id;
    }

    /**
     * Constructs a <code>FeeStationTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeeStationTransfer} obj Optional instance to populate.
     * @return {module:model/FeeStationTransfer} The populated <code>FeeStationTransfer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeeStationTransfer();

            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('destination')) {
                obj['destination'] = FeeStationDestination.constructFromObject(data['destination']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FeeStationTransfer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FeeStationTransfer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FeeStationTransfer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // validate the optional field `destination`
        if (data['destination']) { // data not null
          if (!!FeeStationDestination.validateJSON) {
            FeeStationDestination.validateJSON(data['destination']);
          }
        }

        return true;
    }


}

FeeStationTransfer.RequiredProperties = ["token_id"];

/**
 * The token ID of the transferred token. You can retrieve the IDs of all the tokens you can use by calling [List enabled tokens](https://www.cobo.com/developers/v2/api-references/wallets/list-enabled-tokens).
 * @member {String} token_id
 */
FeeStationTransfer.prototype['token_id'] = undefined;

/**
 * @member {module:model/FeeStationDestination} destination
 */
FeeStationTransfer.prototype['destination'] = undefined;






export default FeeStationTransfer;

