/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SOLComputeUnit model module.
 * @module model/SOLComputeUnit
 */
class SOLComputeUnit {
    /**
     * Constructs a new <code>SOLComputeUnit</code>.
     * The transaction gas price based on the SOL fee model.
     * @alias module:model/SOLComputeUnit
     */
    constructor() { 
        
        SOLComputeUnit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SOLComputeUnit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SOLComputeUnit} obj Optional instance to populate.
     * @return {module:model/SOLComputeUnit} The populated <code>SOLComputeUnit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SOLComputeUnit();

            if (data.hasOwnProperty('compute_unit_price')) {
                obj['compute_unit_price'] = ApiClient.convertToType(data['compute_unit_price'], 'String');
            }
            if (data.hasOwnProperty('compute_unit_limit')) {
                obj['compute_unit_limit'] = ApiClient.convertToType(data['compute_unit_limit'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SOLComputeUnit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SOLComputeUnit</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['compute_unit_price'] && !(typeof data['compute_unit_price'] === 'string' || data['compute_unit_price'] instanceof String)) {
            throw new Error("Expected the field `compute_unit_price` to be a primitive type in the JSON string but got " + data['compute_unit_price']);
        }
        // ensure the json data is a string
        if (data['compute_unit_limit'] && !(typeof data['compute_unit_limit'] === 'string' || data['compute_unit_limit'] instanceof String)) {
            throw new Error("Expected the field `compute_unit_limit` to be a primitive type in the JSON string but got " + data['compute_unit_limit']);
        }

        return true;
    }


}



/**
 * The cost per compute unit. Transactions consume computational resources measured in compute units, and this price helps determine the cost of executing transactions, especially complex ones involving smart contracts.
 * @member {String} compute_unit_price
 */
SOLComputeUnit.prototype['compute_unit_price'] = undefined;

/**
 * The maximum number of compute units allowed for a transaction. This limits the resources any single transaction can consume, preventing excessive resource usage that could impact network performance negatively.
 * @member {String} compute_unit_limit
 */
SOLComputeUnit.prototype['compute_unit_limit'] = undefined;






export default SOLComputeUnit;

