/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenizationMpcOperationSource from './TokenizationMpcOperationSource';
import TokenizationOperationSourceType from './TokenizationOperationSourceType';
import TokenizationWeb3OperationSource from './TokenizationWeb3OperationSource';

/**
 * The TokenizationTokenOperationSource model module.
 * @module model/TokenizationTokenOperationSource
 */
class TokenizationTokenOperationSource {
    /**
     * Constructs a new <code>TokenizationTokenOperationSource</code>.
     * @alias module:model/TokenizationTokenOperationSource
     * @param {(module:model/TokenizationMpcOperationSource|module:model/TokenizationWeb3OperationSource)} instance The actual instance to initialize TokenizationTokenOperationSource.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        var discriminatorValue = instance["source_type"];

        if (discriminatorValue) {
            switch(discriminatorValue) {
                case "Org-Controlled":
                    this.actualInstance = TokenizationMpcOperationSource.constructFromObject(instance);
                    match++;
                    break;
                case "Web3":
                    this.actualInstance = TokenizationWeb3OperationSource.constructFromObject(instance);
                    match++;
                    break;
                default:
                    errorMessages.push("Unrecognized discriminator value: " + discriminatorValue);
                    break;
            }
            return;
        }

        try {
            if (instance instanceof TokenizationMpcOperationSource) {
                this.actualInstance = instance;
            } else if(!!TokenizationMpcOperationSource.validateJSON && TokenizationMpcOperationSource.validateJSON(instance)){
                // plain JS object
                // create TokenizationMpcOperationSource from JS object
                this.actualInstance = TokenizationMpcOperationSource.constructFromObject(instance);
            } else {
                if(TokenizationMpcOperationSource.constructFromObject(instance)) {
                    if (!!TokenizationMpcOperationSource.constructFromObject(instance).toJSON) {
                        if (TokenizationMpcOperationSource.constructFromObject(instance).toJSON()) {
                            this.actualInstance = TokenizationMpcOperationSource.constructFromObject(instance);
                        }
                    } else {
                        this.actualInstance = TokenizationMpcOperationSource.constructFromObject(instance);
                    }
                }

            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TokenizationMpcOperationSource
            errorMessages.push("Failed to construct TokenizationMpcOperationSource: " + err)
        }

        try {
            if (instance instanceof TokenizationWeb3OperationSource) {
                this.actualInstance = instance;
            } else if(!!TokenizationWeb3OperationSource.validateJSON && TokenizationWeb3OperationSource.validateJSON(instance)){
                // plain JS object
                // create TokenizationWeb3OperationSource from JS object
                this.actualInstance = TokenizationWeb3OperationSource.constructFromObject(instance);
            } else {
                if(TokenizationWeb3OperationSource.constructFromObject(instance)) {
                    if (!!TokenizationWeb3OperationSource.constructFromObject(instance).toJSON) {
                        if (TokenizationWeb3OperationSource.constructFromObject(instance).toJSON()) {
                            this.actualInstance = TokenizationWeb3OperationSource.constructFromObject(instance);
                        }
                    } else {
                        this.actualInstance = TokenizationWeb3OperationSource.constructFromObject(instance);
                    }
                }

            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TokenizationWeb3OperationSource
            errorMessages.push("Failed to construct TokenizationWeb3OperationSource: " + err)
        }

        // if (match > 1) {
        //    throw new Error("Multiple matches found constructing `TokenizationTokenOperationSource` with oneOf schemas TokenizationMpcOperationSource, TokenizationWeb3OperationSource. Input: " + JSON.stringify(instance));
        // } else
        if (match === 0) {
        //    this.actualInstance = null; // clear the actual instance in case there are multiple matches
        //    throw new Error("No match found constructing `TokenizationTokenOperationSource` with oneOf schemas TokenizationMpcOperationSource, TokenizationWeb3OperationSource. Details: " +
        //                    errorMessages.join(", "));
        return;
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>TokenizationTokenOperationSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenizationTokenOperationSource} obj Optional instance to populate.
     * @return {module:model/TokenizationTokenOperationSource} The populated <code>TokenizationTokenOperationSource</code> instance.
     */
    static constructFromObject(data, obj) {
        return new TokenizationTokenOperationSource(data);
    }

    /**
     * Gets the actual instance, which can be <code>TokenizationMpcOperationSource</code>, <code>TokenizationWeb3OperationSource</code>.
     * @return {(module:model/TokenizationMpcOperationSource|module:model/TokenizationWeb3OperationSource)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>TokenizationMpcOperationSource</code>, <code>TokenizationWeb3OperationSource</code>.
     * @param {(module:model/TokenizationMpcOperationSource|module:model/TokenizationWeb3OperationSource)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = TokenizationTokenOperationSource.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of TokenizationTokenOperationSource from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/TokenizationTokenOperationSource} An instance of TokenizationTokenOperationSource.
     */
    static fromJSON = function(json_string){
        return TokenizationTokenOperationSource.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/TokenizationOperationSourceType} source_type
 */
TokenizationTokenOperationSource.prototype['source_type'] = undefined;

/**
 * The wallet ID.
 * @member {String} wallet_id
 */
TokenizationTokenOperationSource.prototype['wallet_id'] = undefined;

/**
 * The wallet address to interact with the token contract from.
 * @member {String} address
 */
TokenizationTokenOperationSource.prototype['address'] = undefined;


TokenizationTokenOperationSource.OneOf = ["TokenizationMpcOperationSource", "TokenizationWeb3OperationSource"];

export default TokenizationTokenOperationSource;

