/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenizationTokenOperationSource from './TokenizationTokenOperationSource';

/**
 * The TokenizationAllowlistActivationParams model module.
 * @module model/TokenizationAllowlistActivationParams
 */
class TokenizationAllowlistActivationParams {
    /**
     * Constructs a new <code>TokenizationAllowlistActivationParams</code>.
     * @alias module:model/TokenizationAllowlistActivationParams
     * @param source {module:model/TokenizationTokenOperationSource} 
     * @param activation {Boolean} Whether to activate the allowlist feature for the token.
     */
    constructor(source, activation) { 
        
        TokenizationAllowlistActivationParams.initialize(this, source, activation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, source, activation) { 
        obj['source'] = source;
        obj['activation'] = activation;
    }

    /**
     * Constructs a <code>TokenizationAllowlistActivationParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenizationAllowlistActivationParams} obj Optional instance to populate.
     * @return {module:model/TokenizationAllowlistActivationParams} The populated <code>TokenizationAllowlistActivationParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenizationAllowlistActivationParams();

            if (data.hasOwnProperty('source')) {
                obj['source'] = TokenizationTokenOperationSource.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('activation')) {
                obj['activation'] = ApiClient.convertToType(data['activation'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenizationAllowlistActivationParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenizationAllowlistActivationParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenizationAllowlistActivationParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `source`
        if (data['source']) { // data not null
          if (!!TokenizationTokenOperationSource.validateJSON) {
            TokenizationTokenOperationSource.validateJSON(data['source']);
          }
        }

        return true;
    }


}

TokenizationAllowlistActivationParams.RequiredProperties = ["source", "activation"];

/**
 * @member {module:model/TokenizationTokenOperationSource} source
 */
TokenizationAllowlistActivationParams.prototype['source'] = undefined;

/**
 * Whether to activate the allowlist feature for the token.
 * @member {Boolean} activation
 */
TokenizationAllowlistActivationParams.prototype['activation'] = undefined;






export default TokenizationAllowlistActivationParams;

