/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionDestinationType from './TransactionDestinationType';

/**
 * The TransactionMessageSignBTCEIP191Destination model module.
 * @module model/TransactionMessageSignBTCEIP191Destination
 */
class TransactionMessageSignBTCEIP191Destination {
    /**
     * Constructs a new <code>TransactionMessageSignBTCEIP191Destination</code>.
     * The information about the destination &#x60;BTC_EIP_191_Signature&#x60;. Refer to [Transaction sources and destinations](https://www.cobo.com/developers/v2/guides/transactions/sources-and-destinations) for a detailed introduction about the supported sources and destinations for each transaction type.
     * @alias module:model/TransactionMessageSignBTCEIP191Destination
     * @param destination_type {module:model/TransactionDestinationType} 
     * @param message {String} The raw data of the message to be signed, encoded in Base64 format.
     */
    constructor(destination_type, message) { 
        
        TransactionMessageSignBTCEIP191Destination.initialize(this, destination_type, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, destination_type, message) { 
        obj['destination_type'] = destination_type;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>TransactionMessageSignBTCEIP191Destination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionMessageSignBTCEIP191Destination} obj Optional instance to populate.
     * @return {module:model/TransactionMessageSignBTCEIP191Destination} The populated <code>TransactionMessageSignBTCEIP191Destination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionMessageSignBTCEIP191Destination();

            if (data.hasOwnProperty('destination_type')) {
                obj['destination_type'] = TransactionDestinationType.constructFromObject(data['destination_type']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionMessageSignBTCEIP191Destination</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionMessageSignBTCEIP191Destination</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransactionMessageSignBTCEIP191Destination.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

TransactionMessageSignBTCEIP191Destination.RequiredProperties = ["destination_type", "message"];

/**
 * @member {module:model/TransactionDestinationType} destination_type
 */
TransactionMessageSignBTCEIP191Destination.prototype['destination_type'] = undefined;

/**
 * The raw data of the message to be signed, encoded in Base64 format.
 * @member {String} message
 */
TransactionMessageSignBTCEIP191Destination.prototype['message'] = undefined;






export default TransactionMessageSignBTCEIP191Destination;

