/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TSSCallbackRequestType.
* @enum {}
* @readonly
*/
export default class TSSCallbackRequestType {
    
        /**
         * value: 0
         * @const
         */
        "PING" = 0;

    
        /**
         * value: 1
         * @const
         */
        "KEYGEN" = 1;

    
        /**
         * value: 2
         * @const
         */
        "KEYSIGN" = 2;

    
        /**
         * value: 3
         * @const
         */
        "KEYRESHARE" = 3;

    
        /**
         * value: 5
         * @const
         */
        "KEYSHARESIGN" = 5;

    
        /**
         * value: 11184809
         * @const
         */
        "unknown_default_open_api" = 11184809;

    

    /**
    * Returns a <code>TSSCallbackRequestType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TSSCallbackRequestType} The enum <code>TSSCallbackRequestType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

