/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TSSEventDataType.
* @enum {}
* @readonly
*/
export default class TSSEventDataType {
    
        /**
         * value: "KeyGen"
         * @const
         */
        "KeyGen" = "KeyGen";

    
        /**
         * value: "KeyReshare"
         * @const
         */
        "KeyReshare" = "KeyReshare";

    
        /**
         * value: "KeySign"
         * @const
         */
        "KeySign" = "KeySign";

    
        /**
         * value: "KeyShareSign"
         * @const
         */
        "KeyShareSign" = "KeyShareSign";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>TSSEventDataType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TSSEventDataType} The enum <code>TSSEventDataType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

