/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TSSSignature model module.
 * @module model/TSSSignature
 */
class TSSSignature {
    /**
     * Constructs a new <code>TSSSignature</code>.
     * @alias module:model/TSSSignature
     */
    constructor() { 
        
        TSSSignature.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TSSSignature</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TSSSignature} obj Optional instance to populate.
     * @return {module:model/TSSSignature} The populated <code>TSSSignature</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TSSSignature();

            if (data.hasOwnProperty('bip32_path')) {
                obj['bip32_path'] = ApiClient.convertToType(data['bip32_path'], 'String');
            }
            if (data.hasOwnProperty('msg_hash')) {
                obj['msg_hash'] = ApiClient.convertToType(data['msg_hash'], 'String');
            }
            if (data.hasOwnProperty('tweak')) {
                obj['tweak'] = ApiClient.convertToType(data['tweak'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signature_recovery')) {
                obj['signature_recovery'] = ApiClient.convertToType(data['signature_recovery'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TSSSignature</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TSSSignature</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['bip32_path'] && !(typeof data['bip32_path'] === 'string' || data['bip32_path'] instanceof String)) {
            throw new Error("Expected the field `bip32_path` to be a primitive type in the JSON string but got " + data['bip32_path']);
        }
        // ensure the json data is a string
        if (data['msg_hash'] && !(typeof data['msg_hash'] === 'string' || data['msg_hash'] instanceof String)) {
            throw new Error("Expected the field `msg_hash` to be a primitive type in the JSON string but got " + data['msg_hash']);
        }
        // ensure the json data is a string
        if (data['tweak'] && !(typeof data['tweak'] === 'string' || data['tweak'] instanceof String)) {
            throw new Error("Expected the field `tweak` to be a primitive type in the JSON string but got " + data['tweak']);
        }
        // ensure the json data is a string
        if (data['signature'] && !(typeof data['signature'] === 'string' || data['signature'] instanceof String)) {
            throw new Error("Expected the field `signature` to be a primitive type in the JSON string but got " + data['signature']);
        }
        // ensure the json data is a string
        if (data['signature_recovery'] && !(typeof data['signature_recovery'] === 'string' || data['signature_recovery'] instanceof String)) {
            throw new Error("Expected the field `signature_recovery` to be a primitive type in the JSON string but got " + data['signature_recovery']);
        }

        return true;
    }


}



/**
 * The BIP32 path.
 * @member {String} bip32_path
 */
TSSSignature.prototype['bip32_path'] = undefined;

/**
 * The message hash.
 * @member {String} msg_hash
 */
TSSSignature.prototype['msg_hash'] = undefined;

/**
 * The tweak.
 * @member {String} tweak
 */
TSSSignature.prototype['tweak'] = undefined;

/**
 * The signature.
 * @member {String} signature
 */
TSSSignature.prototype['signature'] = undefined;

/**
 * The signature recovery.
 * @member {String} signature_recovery
 */
TSSSignature.prototype['signature_recovery'] = undefined;






export default TSSSignature;

