/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WalletType from './WalletType';

/**
 * The UpdateMpcWalletParams model module.
 * @module model/UpdateMpcWalletParams
 */
class UpdateMpcWalletParams {
    /**
     * Constructs a new <code>UpdateMpcWalletParams</code>.
     * The information of MPC Wallets.
     * @alias module:model/UpdateMpcWalletParams
     * @param wallet_type {module:model/WalletType} 
     */
    constructor(wallet_type) { 
        
        UpdateMpcWalletParams.initialize(this, wallet_type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wallet_type) { 
        obj['wallet_type'] = wallet_type;
    }

    /**
     * Constructs a <code>UpdateMpcWalletParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateMpcWalletParams} obj Optional instance to populate.
     * @return {module:model/UpdateMpcWalletParams} The populated <code>UpdateMpcWalletParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateMpcWalletParams();

            if (data.hasOwnProperty('wallet_type')) {
                obj['wallet_type'] = WalletType.constructFromObject(data['wallet_type']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateMpcWalletParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateMpcWalletParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateMpcWalletParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

UpdateMpcWalletParams.RequiredProperties = ["wallet_type"];

/**
 * @member {module:model/WalletType} wallet_type
 */
UpdateMpcWalletParams.prototype['wallet_type'] = undefined;

/**
 * The wallet name.
 * @member {String} name
 */
UpdateMpcWalletParams.prototype['name'] = undefined;






export default UpdateMpcWalletParams;

