/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateMerchantByIdRequest model module.
 * @module model/UpdateMerchantByIdRequest
 */
class UpdateMerchantByIdRequest {
    /**
     * Constructs a new <code>UpdateMerchantByIdRequest</code>.
     * @alias module:model/UpdateMerchantByIdRequest
     */
    constructor() { 
        
        UpdateMerchantByIdRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateMerchantByIdRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateMerchantByIdRequest} obj Optional instance to populate.
     * @return {module:model/UpdateMerchantByIdRequest} The populated <code>UpdateMerchantByIdRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateMerchantByIdRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('developer_fee_rate')) {
                obj['developer_fee_rate'] = ApiClient.convertToType(data['developer_fee_rate'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateMerchantByIdRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateMerchantByIdRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['developer_fee_rate'] && !(typeof data['developer_fee_rate'] === 'string' || data['developer_fee_rate'] instanceof String)) {
            throw new Error("Expected the field `developer_fee_rate` to be a primitive type in the JSON string but got " + data['developer_fee_rate']);
        }

        return true;
    }


}



/**
 * The merchant name.
 * @member {String} name
 */
UpdateMerchantByIdRequest.prototype['name'] = undefined;

/**
 * The fee rate applied when topping up the merchant account. Represented as a string percentage (e.g., \"0.1\" means 10%).
 * @member {String} developer_fee_rate
 */
UpdateMerchantByIdRequest.prototype['developer_fee_rate'] = undefined;






export default UpdateMerchantByIdRequest;

