/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.ApiLogDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiLogDetails', function() {
    it('should create an instance of ApiLogDetails', function() {
      // uncomment below and update the code to test ApiLogDetails
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be.a(CoboWaas2.ApiLogDetails);
    });

    it('should have the property log_id (base name: "log_id")', function() {
      // uncomment below and update the code to test the property log_id
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property api_method (base name: "api_method")', function() {
      // uncomment below and update the code to test the property api_method
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property api_endpoint (base name: "api_endpoint")', function() {
      // uncomment below and update the code to test the property api_endpoint
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property status_code (base name: "status_code")', function() {
      // uncomment below and update the code to test the property status_code
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property ip_address (base name: "ip_address")', function() {
      // uncomment below and update the code to test the property ip_address
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property request_timestamp (base name: "request_timestamp")', function() {
      // uncomment below and update the code to test the property request_timestamp
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property api_key (base name: "api_key")', function() {
      // uncomment below and update the code to test the property api_key
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property response_body (base name: "response_body")', function() {
      // uncomment below and update the code to test the property response_body
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property query_params (base name: "query_params")', function() {
      // uncomment below and update the code to test the property query_params
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

    it('should have the property request_body (base name: "request_body")', function() {
      // uncomment below and update the code to test the property request_body
      //var instance = new CoboWaas2.ApiLogDetails();
      //expect(instance).to.be();
    });

  });

}));
