/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.CoreStakingExtra();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CoreStakingExtra', function() {
    it('should create an instance of CoreStakingExtra', function() {
      // uncomment below and update the code to test CoreStakingExtra
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be.a(CoboWaas2.CoreStakingExtra);
    });

    it('should have the property pool_type (base name: "pool_type")', function() {
      // uncomment below and update the code to test the property pool_type
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

    it('should have the property pos_chain (base name: "pos_chain")', function() {
      // uncomment below and update the code to test the property pos_chain
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

    it('should have the property staker_address (base name: "staker_address")', function() {
      // uncomment below and update the code to test the property staker_address
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

    it('should have the property validator_address (base name: "validator_address")', function() {
      // uncomment below and update the code to test the property validator_address
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

    it('should have the property reward_address (base name: "reward_address")', function() {
      // uncomment below and update the code to test the property reward_address
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

    it('should have the property timelock (base name: "timelock")', function() {
      // uncomment below and update the code to test the property timelock
      //var instance = new CoboWaas2.CoreStakingExtra();
      //expect(instance).to.be();
    });

  });

}));
