/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.GetTopUpAddress200Response();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetTopUpAddress200Response', function() {
    it('should create an instance of GetTopUpAddress200Response', function() {
      // uncomment below and update the code to test GetTopUpAddress200Response
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be.a(CoboWaas2.GetTopUpAddress200Response);
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property payer_id (base name: "payer_id")', function() {
      // uncomment below and update the code to test the property payer_id
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property custom_payer_id (base name: "custom_payer_id")', function() {
      // uncomment below and update the code to test the property custom_payer_id
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property merchant_id (base name: "merchant_id")', function() {
      // uncomment below and update the code to test the property merchant_id
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property token_id (base name: "token_id")', function() {
      // uncomment below and update the code to test the property token_id
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property chain (base name: "chain")', function() {
      // uncomment below and update the code to test the property chain
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property developer_fee_rate (base name: "developer_fee_rate")', function() {
      // uncomment below and update the code to test the property developer_fee_rate
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property min_amount (base name: "min_amount")', function() {
      // uncomment below and update the code to test the property min_amount
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

    it('should have the property updated_timestamp (base name: "updated_timestamp")', function() {
      // uncomment below and update the code to test the property updated_timestamp
      //var instance = new CoboWaas2.GetTopUpAddress200Response();
      //expect(instance).to.be();
    });

  });

}));
