/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.TokenizationSOLTokenParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TokenizationSOLTokenParams', function() {
    it('should create an instance of TokenizationSOLTokenParams', function() {
      // uncomment below and update the code to test TokenizationSOLTokenParams
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be.a(CoboWaas2.TokenizationSOLTokenParams);
    });

    it('should have the property standard (base name: "standard")', function() {
      // uncomment below and update the code to test the property standard
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property decimals (base name: "decimals")', function() {
      // uncomment below and update the code to test the property decimals
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property token_access_activated (base name: "token_access_activated")', function() {
      // uncomment below and update the code to test the property token_access_activated
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

    it('should have the property permissions (base name: "permissions")', function() {
      // uncomment below and update the code to test the property permissions
      //var instance = new CoboWaas2.TokenizationSOLTokenParams();
      //expect(instance).to.be();
    });

  });

}));
