/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.TransactionRoleApprovalDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionRoleApprovalDetail', function() {
    it('should create an instance of TransactionRoleApprovalDetail', function() {
      // uncomment below and update the code to test TransactionRoleApprovalDetail
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be.a(CoboWaas2.TransactionRoleApprovalDetail);
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property review_threshold (base name: "review_threshold")', function() {
      // uncomment below and update the code to test the property review_threshold
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property initiator (base name: "initiator")', function() {
      // uncomment below and update the code to test the property initiator
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property complete_time (base name: "complete_time")', function() {
      // uncomment below and update the code to test the property complete_time
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property user_details (base name: "user_details")', function() {
      // uncomment below and update the code to test the property user_details
      //var instance = new CoboWaas2.TransactionRoleApprovalDetail();
      //expect(instance).to.be();
    });

  });

}));
