/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.TransactionUserApprovalDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionUserApprovalDetail', function() {
    it('should create an instance of TransactionUserApprovalDetail', function() {
      // uncomment below and update the code to test TransactionUserApprovalDetail
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be.a(CoboWaas2.TransactionUserApprovalDetail);
    });

    it('should have the property pubkey (base name: "pubkey")', function() {
      // uncomment below and update the code to test the property pubkey
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property result (base name: "result")', function() {
      // uncomment below and update the code to test the property result
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property signature (base name: "signature")', function() {
      // uncomment below and update the code to test the property signature
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property message_version (base name: "message_version")', function() {
      // uncomment below and update the code to test the property message_version
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

    it('should have the property extra_message (base name: "extra_message")', function() {
      // uncomment below and update the code to test the property extra_message
      //var instance = new CoboWaas2.TransactionUserApprovalDetail();
      //expect(instance).to.be();
    });

  });

}));
