/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.TransactionExtra();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionExtra', function() {
    it('should create an instance of TransactionExtra', function() {
      // uncomment below and update the code to test TransactionExtra
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be.a(CoboWaas2.TransactionExtra);
    });

    it('should have the property extra_type (base name: "extra_type")', function() {
      // uncomment below and update the code to test the property extra_type
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property babylon_address_info (base name: "babylon_address_info")', function() {
      // uncomment below and update the code to test the property babylon_address_info
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property btc_address_info (base name: "btc_address_info")', function() {
      // uncomment below and update the code to test the property btc_address_info
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property stake_amount (base name: "stake_amount")', function() {
      // uncomment below and update the code to test the property stake_amount
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property finality_provider_public_key (base name: "finality_provider_public_key")', function() {
      // uncomment below and update the code to test the property finality_provider_public_key
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property stake_block_time (base name: "stake_block_time")', function() {
      // uncomment below and update the code to test the property stake_block_time
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property param_version (base name: "param_version")', function() {
      // uncomment below and update the code to test the property param_version
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property withdraw_from_type (base name: "withdraw_from_type")', function() {
      // uncomment below and update the code to test the property withdraw_from_type
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property slash_from_type (base name: "slash_from_type")', function() {
      // uncomment below and update the code to test the property slash_from_type
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property timelock (base name: "timelock")', function() {
      // uncomment below and update the code to test the property timelock
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property change_address (base name: "change_address")', function() {
      // uncomment below and update the code to test the property change_address
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property validator_address (base name: "validator_address")', function() {
      // uncomment below and update the code to test the property validator_address
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

    it('should have the property reward_address (base name: "reward_address")', function() {
      // uncomment below and update the code to test the property reward_address
      //var instance = new CoboWaas2.TransactionExtra();
      //expect(instance).to.be();
    });

  });

}));
