/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.TSSKeySignRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TSSKeySignRequest', function() {
    it('should create an instance of TSSKeySignRequest', function() {
      // uncomment below and update the code to test TSSKeySignRequest
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be.a(CoboWaas2.TSSKeySignRequest);
    });

    it('should have the property group_id (base name: "group_id")', function() {
      // uncomment below and update the code to test the property group_id
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property root_pub_key (base name: "root_pub_key")', function() {
      // uncomment below and update the code to test the property root_pub_key
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property used_node_ids (base name: "used_node_ids")', function() {
      // uncomment below and update the code to test the property used_node_ids
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property bip32_path_list (base name: "bip32_path_list")', function() {
      // uncomment below and update the code to test the property bip32_path_list
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property msg_hash_list (base name: "msg_hash_list")', function() {
      // uncomment below and update the code to test the property msg_hash_list
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property tweak_list (base name: "tweak_list")', function() {
      // uncomment below and update the code to test the property tweak_list
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property signature_type (base name: "signature_type")', function() {
      // uncomment below and update the code to test the property signature_type
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property tss_protocol (base name: "tss_protocol")', function() {
      // uncomment below and update the code to test the property tss_protocol
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property task_id (base name: "task_id")', function() {
      // uncomment below and update the code to test the property task_id
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

    it('should have the property biz_task_id (base name: "biz_task_id")', function() {
      // uncomment below and update the code to test the property biz_task_id
      //var instance = new CoboWaas2.TSSKeySignRequest();
      //expect(instance).to.be();
    });

  });

}));
